### PR TITLE
Delete index.html

### PR DESCRIPTION
**Pull request by Svitlana007**

### CODE REVIEW

**Comment by atherdon** [comment]
we dont need to delete those files from this repo. I'm just trying to
organize templates that we want to implement and put them at one place in
our documentation website. Sorry for not clarifying it before.

**Comment by Svitlana007** [comment]
> we dont need to delete those files from this repo. I'm just trying to organize templates that we want to implement and put them at one place in our documentation website. Sorry for not clarifying it before.
> […](#)
> Message ID: ***@***.***>

sorry(((...

**Comment by atherdon** [comment]
no problem at all. btw, we probably will work and organize things inside of this repository at some point.
doing something similar to changes that we did at awesome-email-marketing repository

**Comment by Svitlana007** [comment]
> no problem at all. btw, we probably will work and organize things inside of this repository at some point.
> doing something similar to changes that we did at awesome-email-marketing repository

без проблем, я тільки за! Нарізайте задачі!)

**Comment by atherdon** [comment]
зараз хочу завести нашу content factory спочатку. також маю интерна, яка мабуть допоможе з react - тому ми почали ту частину робити

**Pull request closed without merging**
